name: Central Infra Deployment

on:
  repository_dispatch:
    types: [ deploy-infra ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up inputs
        run: |
          echo "CLIENT_NAME=${{ github.event.client_name }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.environment }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var="client_name=${{ env.CLIENT_NAME }}" -var="environment=${{ env.ENVIRONMENT }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="client_name=${{ env.CLIENT_NAME }}" -var="environment=${{ env.ENVIRONMENT }}"
